# makes the console more noisy
verbose = false
# default timeout is used in situations where a per request timeout is not specified
default_timeout = "5m"
# the listen endpoint
listen = "127.0.0.1:8089"

# now you can add as many executables as you would like
# healthcheck argument is used to ensure the executable is functional prior to exposing it ot the outside world
[executable.date]
path = "/bin/date"
# an empty health check argument disables the health check altogether
healthcheck_argument = ""

[executable.uuid]
path = "/usr/bin/uuidgen"
healthcheck_argument = ""

[executable.curl]
path = "/usr/bin/curl"
healthcheck_argument = "--version"
